<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TestSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('knowledge_bases')->insert([
            [
                'question' => 'Apa itu hubungan kerja?',
                'answer' => 'Hubungan kerja adalah hubungan antara pengusaha dengan pekerja berdasarkan perjanjian kerja yang mempunyai unsur pekerjaan, upah, dan perintah.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 1 angka 15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa perbedaan PKWT dan PKWTT?',
                'answer' => 'PKWT (Perjanjian Kerja Waktu Tertentu) adalah kontrak kerja dengan jangka waktu tertentu, sedangkan PKWTT (Perjanjian Kerja Waktu Tidak Tertentu) adalah kontrak kerja permanen atau tetap.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 56-59, UU No. 11 Tahun 2020 tentang Cipta Kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Berapa jam kerja normal dalam seminggu?',
                'answer' => 'Jam kerja normal adalah 7 jam per hari dan 40 jam per minggu untuk 6 hari kerja, atau 8 jam per hari dan 40 jam per minggu untuk 5 hari kerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 77',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja berhak atas cuti tahunan?',
                'answer' => 'Ya, pekerja yang telah bekerja selama 12 bulan terus menerus berhak atas cuti tahunan sekurang-kurangnya 12 hari kerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 79',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana ketentuan upah minimum?',
                'answer' => 'Upah minimum ditetapkan oleh Gubernur setiap tahun sebagai jaring pengaman agar pekerja tidak menerima upah di bawah standar.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 88C, PP No. 36 Tahun 2021 tentang Pengupahan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja berhak atas THR?',
                'answer' => 'Ya, pekerja berhak atas Tunjangan Hari Raya Keagamaan yang wajib dibayar pengusaha paling lambat 7 hari sebelum hari raya.',
                'sources' => 'Permenaker No. 6 Tahun 2016 tentang THR Keagamaan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana aturan lembur di Indonesia?',
                'answer' => 'Kerja lembur hanya boleh dilakukan paling banyak 4 jam per hari dan 18 jam per minggu dengan persetujuan pekerja dan wajib dibayar.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 78, PP No. 35 Tahun 2021',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa itu PHK?',
                'answer' => 'Pemutusan Hubungan Kerja (PHK) adalah berakhirnya hubungan kerja karena suatu hal tertentu yang mengakibatkan berakhirnya hak dan kewajiban antara pekerja dengan pengusaha.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 1 angka 25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa hak pekerja yang terkena PHK?',
                'answer' => 'Pekerja berhak atas uang pesangon, uang penghargaan masa kerja, dan uang penggantian hak sesuai ketentuan undang-undang.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 156',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja kontrak berhak atas pesangon?',
                'answer' => 'Pekerja kontrak (PKWT) tidak berhak atas pesangon, tetapi berhak atas uang kompensasi di akhir kontrak.',
                'sources' => 'UU No. 11 Tahun 2020 tentang Cipta Kerja, PP No. 35 Tahun 2021 Pasal 15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja magang diakui dalam hukum ketenagakerjaan?',
                'answer' => 'Ya, pemagangan diatur dalam perjanjian tertulis antara peserta magang dengan perusahaan dan tidak menimbulkan hubungan kerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 21, PP No. 36 Tahun 2016',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja perempuan berhak atas cuti melahirkan?',
                'answer' => 'Ya, pekerja perempuan berhak cuti 1,5 bulan sebelum dan 1,5 bulan sesudah melahirkan.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 82',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja sakit tetap menerima upah?',
                'answer' => 'Ya, pekerja yang sakit tetap berhak atas upah dengan persentase tertentu sesuai lama sakit.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 93',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana aturan cuti haid untuk pekerja perempuan?',
                'answer' => 'Pekerja perempuan yang dalam masa haid dan merasa sakit dapat tidak masuk kerja pada hari pertama dan kedua, dengan tetap mendapat upah.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 81',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa itu serikat pekerja?',
                'answer' => 'Serikat pekerja adalah organisasi yang dibentuk dari, oleh, dan untuk pekerja baik di perusahaan maupun di luar perusahaan guna memperjuangkan hak-hak pekerja.',
                'sources' => 'UU No. 21 Tahun 2000 tentang Serikat Pekerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja harian lepas dilindungi undang-undang?',
                'answer' => 'Ya, pekerja harian lepas tetap dilindungi hukum sepanjang memenuhi unsur hubungan kerja.',
                'sources' => 'UU No. 13 Tahun 2003, Putusan MA No. 150 K/Pdt.Sus-PHI/2014',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana ketentuan outsourcing di Indonesia?',
                'answer' => 'Outsourcing hanya boleh dilakukan untuk kegiatan penunjang, dengan jaminan perlindungan hak pekerja.',
                'sources' => 'UU No. 11 Tahun 2020 tentang Cipta Kerja, PP No. 35 Tahun 2021',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja berhak atas BPJS Ketenagakerjaan?',
                'answer' => 'Ya, setiap pekerja berhak atas jaminan sosial tenaga kerja seperti JKK, JKM, JHT, dan JP.',
                'sources' => 'UU No. 24 Tahun 2011 tentang BPJS, PP No. 46 Tahun 2015',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana penyelesaian perselisihan hubungan industrial?',
                'answer' => 'Perselisihan hubungan industrial diselesaikan melalui bipartit, mediasi, konsiliasi, arbitrase, atau pengadilan hubungan industrial.',
                'sources' => 'UU No. 2 Tahun 2004 tentang Penyelesaian Perselisihan Hubungan Industrial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja anak diperbolehkan?',
                'answer' => 'Pekerja anak dilarang, kecuali untuk pekerjaan ringan dengan syarat khusus dan pengawasan ketat.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 68-75',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa syarat sah perjanjian kerja?',
                'answer' => 'Perjanjian kerja sah apabila dibuat atas dasar kesepakatan, kecakapan, adanya pekerjaan, serta pekerjaan yang diperjanjikan tidak bertentangan dengan hukum.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja boleh dipindahkan sepihak oleh perusahaan?',
                'answer' => 'Pemindahan pekerja (mutasi) hanya sah apabila tidak merugikan pekerja dan tetap memperhatikan hak-hak pekerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana perlindungan untuk pekerja difabel?',
                'answer' => 'Pengusaha wajib mempekerjakan sekurang-kurangnya 1 orang penyandang disabilitas dari setiap 100 pekerja.',
                'sources' => 'UU No. 8 Tahun 2016 tentang Penyandang Disabilitas Pasal 53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja berhak menolak lembur?',
                'answer' => 'Ya, pekerja berhak menolak lembur jika tidak ada persetujuan tertulis atau perintah kerja lembur dari pengusaha.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 78',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja harian lepas berhak atas cuti?',
                'answer' => 'Pekerja harian lepas berhak cuti jika masa kerjanya telah memenuhi syarat minimal 12 bulan berturut-turut.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 79',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa itu uang penghargaan masa kerja?',
                'answer' => 'Uang penghargaan masa kerja adalah kompensasi yang diberikan kepada pekerja yang di-PHK berdasarkan lama masa kerjanya.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 156 ayat (3)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa itu uang penggantian hak?',
                'answer' => 'Uang penggantian hak diberikan kepada pekerja yang di-PHK, meliputi cuti tahunan yang belum diambil, biaya pulang, dan hal lain sesuai perjanjian kerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 156 ayat (4)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja PKWT dapat diputus sebelum kontrak berakhir?',
                'answer' => 'Jika kontrak diputus sebelum waktunya, pihak yang memutus wajib membayar ganti rugi sebesar sisa masa kontrak.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja outsourcing berhak atas jaminan sosial?',
                'answer' => 'Ya, pekerja outsourcing berhak didaftarkan BPJS oleh perusahaan outsourcing.',
                'sources' => 'PP No. 35 Tahun 2021 Pasal 19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa itu perjanjian kerja bersama (PKB)?',
                'answer' => 'PKB adalah perjanjian hasil perundingan antara serikat pekerja dan pengusaha yang memuat syarat kerja, hak, dan kewajiban kedua belah pihak.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 116',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja dapat mogok kerja?',
                'answer' => 'Ya, mogok kerja sah apabila dilakukan sebagai akibat gagalnya perundingan dan diberitahukan secara tertulis kepada pengusaha dan instansi terkait.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 137-138',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa kewajiban perusahaan terhadap pekerja asing?',
                'answer' => 'Perusahaan wajib memiliki izin penggunaan tenaga kerja asing (IMTA) dan wajib menunjuk tenaga kerja Indonesia sebagai pendamping.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 42, PP No. 34 Tahun 2021',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja boleh dipotong upahnya?',
                'answer' => 'Upah tidak boleh dipotong, kecuali untuk potongan tertentu seperti iuran BPJS, koperasi, atau denda yang telah diatur.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 90-91',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa hak pekerja perempuan saat menyusui?',
                'answer' => 'Pekerja perempuan berhak mendapat waktu istirahat untuk menyusui atau memerah ASI selama jam kerja.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 83',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana perlindungan terhadap pekerja yang mengalami kecelakaan kerja?',
                'answer' => 'Pekerja yang mengalami kecelakaan kerja berhak atas perawatan medis, santunan, dan jaminan kecelakaan kerja dari BPJS.',
                'sources' => 'UU No. 24 Tahun 2011 tentang BPJS, PP No. 44 Tahun 2015',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja borongan diatur dalam hukum?',
                'answer' => 'Ya, pekerjaan borongan tetap diakui sepanjang memenuhi unsur hubungan kerja, meskipun dibayar berdasarkan hasil.',
                'sources' => 'UU No. 13 Tahun 2003, praktik yurisprudensi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apa kewajiban pengusaha terkait K3?',
                'answer' => 'Pengusaha wajib menerapkan sistem manajemen keselamatan dan kesehatan kerja (K3) untuk melindungi pekerja.',
                'sources' => 'UU No. 1 Tahun 1970 tentang Keselamatan Kerja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja berhak mendapatkan uang pisah?',
                'answer' => 'Ya, uang pisah diberikan kepada pekerja yang mengundurkan diri secara baik-baik sesuai aturan perusahaan.',
                'sources' => 'PP No. 35 Tahun 2021 Pasal 36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Apakah pekerja dengan masa percobaan dilindungi undang-undang?',
                'answer' => 'Ya, masa percobaan kerja hanya berlaku untuk pekerja PKWTT dan paling lama 3 bulan, dengan tetap dibayar upah.',
                'sources' => 'UU No. 13 Tahun 2003 Pasal 60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Bagaimana aturan pekerja waktu paruh (part-time)?',
                'answer' => 'Pekerja part-time tetap dilindungi sepanjang ada hubungan kerja, meski jam kerjanya lebih sedikit.',
                'sources' => 'UU No. 13 Tahun 2003, PP No. 35 Tahun 2021',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
